BizMall/src/BizMall/Controllers/AdminArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using BizMall.Data.Repositories.Abstract;
using BizMall.ViewModels.AdminCompanyArticles;
using BizMall.Models.CompanyModels;
using BizMall.Models.CommonModels;
using BizMall.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using ArticleList.Models.CommonModels;
using Microsoft.Extensions.Options;

namespace BizMall.Controllers
{
    /// <summary>
    /// ctor
    /// </summary>
    [Authorize]
    public class AdminArticlesController : Controller
    {
        private readonly IRepositoryUser _repositoryUser;
        private readonly IRepositoryCompany _repositoryCompany;
        private readonly IRepositoryArticle _repositoryArticle;
        private readonly IRepositoryImage _repositoryImage;
        private readonly IRepositoryKW _repositoryKW;
        private readonly IRepositoryCategory _repositoryCategory;
        private readonly AppSettings _settings;

        public AdminArticlesController(IRepositoryUser repositoryUser,
                                            IRepositoryCompany repositoryCompany,
                                            IRepositoryArticle repositoryArticle,
                                            IRepositoryImage repositoryImage,
                                            IRepositoryKW repositoryKW,
                                            IRepositoryCategory repositoryCategory,
                                            IOptions<AppSettings> settings)
        {
            _repositoryUser = repositoryUser;
            _repositoryCompany = repositoryCompany;
            _repositoryArticle = repositoryArticle;
            _repositoryImage = repositoryImage;
            _repositoryKW = repositoryKW;
            _repositoryCategory = repositoryCategory;
            _settings = settings.Value;
        }

        /// <summary>
        /// выбрать главное изображение товара
        /// </summary>
        /// <param name="GoodId"></param>
        /// <returns></returns>
        public FileContentResult GetGoodMainImage(int GoodId)
        {
            Image image = _repositoryImage.GetGoodImage(GoodId);
            var fcr = File(image.ImageContent, image.ImageMimeType);
            return fcr;
        }

        private ArticleViewModel ConstructAVM(Article item, bool shortDescription)
        {
            ArticleViewModel avm = new ArticleViewModel
            {
                Id = item.Id,
                Title = item.Title,
                EnTitle = item.EnTitle,
                Description = item.Description,
                UpdateTime = item.UpdateTime,
                Category = item.Category,
                CategoryId = item.CategoryId
            };

            return avm;
        }


        /// <summary>
        /// вывод товаров в личный кабинет компании
        /// </summary>
        public IActionResult Articles(string Category, int Page = 1)
        {
            var currentUser = _repositoryUser.GetCurrentUser(User.Identity.Name);

            if (currentUser != null)
            {
                var Company = _repositoryCompany.GetUserCompany(currentUser);

                PagingInfo pagingInfo;
                var Items = _repositoryArticle.CompanyArticlesFullInformation(Company.Id, Category, Page, out pagingInfo).ToList();

                List<ArticleViewModel> ArticlesVM = new List<ArticleViewModel>();
                foreach (var item in Items)
                {
                    var avm = ConstructAVM(item, true);
                    ArticlesVM.Add(avm);
                }

                ViewData["Title"] = _settings.ApplicationTitle + "Администрирование: Статьи";
                ViewData["HeaderTitle"] = _settings.HeaderTitle;
                ViewData["FooterTitle"] = _settings.FooterTitle;
                ViewBag.ArticlesVM = ArticlesVM;
                ViewBag.PagingInfo = pagingInfo;
                ViewBag.ActiveSubMenu = "Статьи";
            }
            else
            {
                Redirect("/");
            }

            return View();
        }

        public IActionResult Search(string searchstring, int Page = 1)
        {
            if (searchstring == null)
                return RedirectToAction("Articles");

            PagingInfo pagingInfo;
            var Items = _repositoryArticle.SearchStringAdminArticlesFullInformation(searchstring, Page, out pagingInfo).ToList();

            List<ArticleViewModel> ArticlesVM = new List<ArticleViewModel>();
            foreach (var item in Items)
            {
                var avm = ConstructAVM(item, true);
                ArticlesVM.Add(avm);
            }

            ViewData["Title"] = _settings.ApplicationTitle + "Поиск: " + searchstring;
            ViewData["HeaderTitle"] = _settings.HeaderTitle;
            ViewData["FooterTitle"] = _settings.FooterTitle;
            ViewBag.ArticlesVM = ArticlesVM;
            ViewBag.PagingInfo = pagingInfo;
            ViewBag.ActiveSubMenu = "Статьи";

            return View();
        }


        /// <summary>
        /// редактирование товара
        /// </summary>
        /// <param name="id"> id товара</param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult EditArticle(int id)
        {
            CreateEditArticleViewModel cegvm = null;
            if (id != 0)
            {
                #region формирование данных статьи для отображения в интерфейсе редактирования
                Article item = _repositoryArticle.GetArticle(id);

                cegvm = new CreateEditArticleViewModel
                {
                    Title = item.Title,
                    EnTitle = item.EnTitle,
                    Description = item.Description,
                    Link = item.Link,
                    HashTags = item.HashTags,
                    Category = item.Category.Title,
                    CategoryId = item.CategoryId,
                    Id = item.Id,
                    metaDescription = item.metaDescription,
                    metaKeyWords = item.metaKeyWords
            };
                if (item.Images.Count != 0)
                {
                    cegvm.MainImageInBase64 = FromByteToBase64Converter.GetImageBase64Src(item.Images.ToList()[0].Image);
                    foreach (var rgi in item.Images)
                    {
                        //для каждого изображения составляем соответствующую модель отображения
                        cegvm.ImageViewModels.Add(
                            new ImageViewModel
                            {
                                GoodId = rgi.GoodId,
                                Id = rgi.ImageId,
                                goodImageIds = rgi.GoodId + "_" + rgi.ImageId,
                                ImageMimeType = rgi.Image.ImageMimeType,
                                ImageInBase64 = FromByteToBase64Converter.GetImageBase64Src(rgi.Image)
                            }
                        );
                        //для каждого изображения оставляем его id в input всех id изображений товара
                        cegvm.goodImagesIds += rgi.ImageId + "_";
                    }
                }
                #endregion


            }
            else
                cegvm = new CreateEditArticleViewModel();

            #region формирование списка ключевиков для САЙТА

            ViewBag.SiteKws = _repositoryKW.Kws(null).ToList();

            #endregion

            ViewData["Title"] = _settings.ApplicationTitle +"Администрирование: Добавление/Редактирование статьи";
            ViewData["HeaderTitle"] = _settings.HeaderTitle;
            ViewData["FooterTitle"] = _settings.FooterTitle;
            ViewBag.ActiveSubMenu = "Статьи";
            return View(cegvm);
        }
        [HttpPost]
        public IActionResult EditArticle(CreateEditArticleViewModel model)
        {
            if (ModelState.IsValid)
            {
                //ТЕКУЩИЙ ПОЛЬЗОВАТЕЛЬ 
                var currentUser = _repositoryUser.GetCurrentUser(User.Identity.Name);

                //ПОЛУЧАЕМ КОМПАНИЮ РОДИТЕЛЯ ОПРЕДЕЛЯЕМУЮ ТЕКУЩИМ ПОЛЬЗОВАТЕЛЕМ 
                Company company = new Company();
                if (currentUser != null)
                    company = _repositoryCompany.GetUserCompany(currentUser);
                else
                    return RedirectToAction("Articles");

                //ФОРМИРУЕМ СПИСОК ИЗОБРАЖЕНИЙ
                List<RelGoodImage> relImages = new List<RelGoodImage>();
                //если строка id изображений непуста тогда формируем список
                if (model.goodImagesIds != null)
                {
                    string[] strImgids = model.goodImagesIds.Trim().Substring(0, model.goodImagesIds.Length - 1).Split('_');
                    foreach (var strImageId in strImgids)
                    {
                        if (strImageId.Length == 0) continue;//это случай когдау товара нет изображений, но в массив все равно попадает распарсеная пустая строка
                        relImages.Add(new RelGoodImage
                        {
                            GoodId = model.Id,
                            ImageId = Convert.ToInt32(strImageId)
                        });
                    }
                }

                //формирование разделителей
                //model.Description = model.Description.Replace("\r\n", "[newstr]");

                _repositoryArticle.SaveArticle(new Article
                {
                    Id = model.Id,
                    Title = model.Title,
                    EnTitle = model.EnTitle,
                    Description = model.Description,
                    Link = model.Link,
                    HashTags = model.HashTags,
                    CategoryId = Convert.ToInt32(model.CategoryId),

BizMall/src/BizMall/Views/Shared/Components/AllCategoriesToFilterEditingArticles/Default.cshtml
@model BizMall.ViewModels.AdminCompanyArticles.CreateEditArticleViewModel

<!--
<script type="text/javascript">

    $(document).ready(function () {
        $(".nestedcat").click(function () {
            var parent = $(this).parent().parent().prev().html();
            var spanbeg = parent.indexOf('<');
            //вырезаем слово родительской категории и соединяем его с названием дочерней категории
            var tmp = parent.substring(0, spanbeg).trim() + "/" + $(this).html();
            tmp = tmp.trim();

            $("#CurrentCatName").val(tmp);
            $("#CurrentCatId").val($(this).attr('id'));
            return;
        });
    });

    $(document).ready(function () {
        $(".cat").click(function () {
            $("#CurrentCatName").val($(this).html());
            $("#CurrentCatId").val($(this).attr('id'));
            return;
        });


    });
</script>
-->


    <nav id="navbar-sub-header" role="navigation" class="navbar navbar-default" style="margin-top:5px;">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapseCat" data-toggle="collapse" class="navbar-toggle">
                <span>Категории</span>
            </button>
        </div>
        <div id="navbarCollapseCat" class="navbar-collapse collapse" style="padding-top: 10px;">
            <ul class="nav navbar-nav">
                <li style="text-align: center;">
                    <a asp-controller="AdminArticles" asp-action="Articles"  style="width:240px;text-align: center;margin: auto;">ВСЕ</a>
                </li>
                @foreach (var topcat in ViewBag.Categories)
                {

                    if (topcat.CategoryId == null)
                    {
                        bool IsParent = false;

                        @foreach (var cat in ViewBag.Categories)
                        {
                            @if (cat.CategoryId == topcat.Id)
                            {
                                IsParent = true;
                                break;
                            }
                        }
                        if (IsParent == true)
                        {
                            <li class="dropdown" style="text-align: center;">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="@topcat.EnTitle" style="border-radius: 4px;padding-top: 5px;width: 240px; margin: auto;">@topcat.Title<b class="caret"></b></a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop"     style="border-radius: 4px;">
                                    @foreach (var chcat in ViewBag.Categories)
                                    {
                                        @if (chcat.CategoryId == topcat.Id)
                                        {
                                            <li>
                                                <a asp-controller="AdminArticles" asp-action="Articles" asp-route-Category="@chcat.EnTitle" style="text-align: center;margin: auto;"><b>@chcat.Title</b></a>
                                            </li>
                                        }
                                    }
                                </ul>
                            </li>
                        }
                        if (IsParent == false)
                        {
                            <li >
                                <a asp-controller="AdminArticles" asp-action="Articles" asp-route-Category="@topcat.EnTitle" style="width:240px;text-align: center;margin: auto;">@topcat.Title</a>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
    </nav>