BizMall/src/BizMall/Controllers/AdminProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using BizMall.Data.Repositories.Abstract;
using BizMall.Models.CompanyModels;
using Microsoft.AspNetCore.Mvc;
using BizMall.ViewModels.AccountViewModels;
using BizMall.Utils;
using BizMall.ViewModels.AdminCompanyArticles;
using Microsoft.AspNetCore.Identity;
using BizMall.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BizMall.Controllers
{
    [Authorize]
    public class AdminProfileController : Controller
    {
        private readonly IRepositoryUser _repositoryUser;
        private readonly IRepositoryCompany _repositoryCompany;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly AppSettings _settings;

        public AdminProfileController(   IRepositoryUser repositoryUser, 
                                                IRepositoryCompany repositoryCompany, 
                                                UserManager<ApplicationUser> userManager, 
                                                SignInManager<ApplicationUser> signInManager,
                                                IOptions<AppSettings> settings) {
            _repositoryUser = repositoryUser;
            _repositoryCompany = repositoryCompany;
            _userManager = userManager;
            _signInManager = signInManager;
            _settings = settings.Value;
        }

        [HttpGet]
        public IActionResult EditProfile()
        {
            ViewBag.ActiveSubMenu = "Профиль";
            ViewData["Title"] = _settings.ApplicationTitle + "Администрирование: Статьи";
            ViewData["HeaderTitle"] = _settings.HeaderTitle;
            ViewData["FooterTitle"] = _settings.FooterTitle;

            var user = _repositoryUser.GetCurrentUser(User.Identity.Name);
            var Company = _repositoryCompany.GetUserCompany(user);

            switch (Company.AccountType)
            {
                case AccountType.Company:
                {
                    #region редирект на view для Company
                     var cecvm = new CreateEditCompanyViewModel
                    {
                        Id = Company.Id,
                        Name = Company.Title,
                        ActivityDescription = Company.Description,
                        Email = Company.ContactEmail,
                        Telephone = Company.Telephone
                    };
                    #region ЗАПИСЬ ИЗОБРАЖЕНИЙ ВО VIEWMODEL
                    if (Company.Images.Count != 0) {
                        cecvm.LogoImageInBase64 = FromByteToBase64Converter.GetImageBase64Src(Company.Images.ToList()[0].Image);
                        foreach (var rci in Company.Images)
                        {
                            //для каждого изображения составляем соответствующую модель отображения
                            cecvm.ImageViewModels.Add(
                                new ImageViewModel
                                {
                                    GoodId = rci.CompanyId,
                                    Id = rci.ImageId,
                                    goodImageIds = rci.CompanyId + "_" + rci.ImageId,
                                    ImageMimeType = rci.Image.ImageMimeType,
                                    ImageInBase64 = FromByteToBase64Converter.GetImageBase64Src(rci.Image)
                                }
                            );
                            //для каждого изображения оставляем его id в input всех id изображений товара
                            cecvm.companyImagesIds += rci.ImageId + "_";
                        }
                    }
                    #endregion
                    return View("CompanyProfileEditView", cecvm);
                    #endregion
                }
                case AccountType.PrivatePerson:
                {
                    #region редирект на view для PrivatePerson
                    var cecvm = new CreateEditCompanyViewModel
                    {
                        Name = Company.Title,
                        ActivityDescription = Company.Description,
                        Email = Company.ContactEmail,
                        Telephone = Company.Telephone
                    };

                    return View("PrivatePersonProfileEditView", cecvm);
                    #endregion
                }
                default: 
                    return View("PrivatePersonProfileEditView");
                    
            }
        }
        [HttpPost]
        public async System.Threading.Tasks.Task<RedirectToActionResult> EditProfile(CreateEditCompanyViewModel model)
        {
            //if (ModelState.IsValid)
            //{
            var user = _repositoryUser.GetCurrentUser(User.Identity.Name);
            var Company = _repositoryCompany.GetUserCompanyWithNoTrackingImages(user);

            #region ФОРМИРУЕМ СПИСОК ИЗОБРАЖЕНИЙ
            //ФОРМИРУЕМ СПИСОК ИЗОБРАЖЕНИЙ
            List<RelCompanyImage> relImages = new List<RelCompanyImage>();
            //если строка id изображений непуста тогда формируем список
            if (model.companyImagesIds != null)
            {
                string[] strImgids = model.companyImagesIds.Trim().Substring(0, model.companyImagesIds.Length - 1).Split('_');
                foreach (var strImageId in strImgids)
                {
                    if (strImageId.Length == 0) continue;//это случай когдау товара нет изображений, но в массив все равно попадает распарсеная пустая строка
                    relImages.Add(new RelCompanyImage
                    {
                        CompanyId = Company.Id,
                        ImageId = Convert.ToInt32(strImageId)
                    });
                }
            }
            #endregion

            //если меняем email
            if (user.Email != model.Email)
            {
                user.Email = model.Email;
                user.UserName = model.Email;
                await _userManager.UpdateAsync(user);
            }

            await _signInManager.SignInAsync(user, isPersistent: false);

            #region ФОРМИРУЕМ ИЗМЕНЕНННУЮ КОМПАНИЮ
            Company.Title = model.Name;
            Company.Description = model.ActivityDescription;
            Company.ContactEmail = model.Email;
            Company.Telephone = model.Telephone;
            Company.Images = relImages;
            #endregion

            _repositoryCompany.SaveCompanyAccount(Company);
            //}
            return RedirectToAction("EditProfile");
        }
    }
}

BizMall/src/BizMall/Views/AdminProfile/CompanyProfileEditView.cshtml
@{
    Layout = "_AdminLayout";
}



@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using BizMall.ViewModels.AccountViewModels

@model BizMall.ViewModels.AccountViewModels.CreateEditCompanyViewModel
@{
    ViewData["Title"] = "Профиль";
}

<h2>@ViewData["Title"]</h2>
@*<script type="text/javascript" >
        function ShowPrivatePersonDataBlock() {
            $("#CompanyDataBlock").hide();
            $("#PrivatePersonDataBlock").show();
        }

        function ShowCompanyDataBlock() {
            $("#CompanyDataBlock").show();
            $("#PrivatePersonDataBlock").hide();
        }
    </script>*@

<form asp-controller="AdminProfile" asp-action="EditProfile" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
    <hr />
    <!--ПЕРЕКЛЮЧАТЕЛЬ КОМПАНИЯ/КЛИЕНТ-->
    <!--<br />
    <div class="form-group">
        <label class="col-md-2 control-label">Я ПРЕДСТАВЛЯЮ:</label>
        <div class="col-md-10">
            <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-success active" onclick="ShowPrivatePersonDataBlock();">
                    <input type="radio" name="options" id="PrivatePerson" autocomplete="off"  checked>
                    Частное лицо
                </label>
                <label class="btn btn-success" onclick="ShowCompanyDataBlock();">
                    <input type="radio" name="options" id="Company" autocomplete="off" >
                    Компания
                </label>
            </div>
        </div>
    </div>
    <br />-->
    <!--Id добавляемого/редактируемого товара-->
    @if (Model.Id != 0)
    {
        <input asp-for="Id" type="hidden" class="form-control" id="Id" readonly="readonly" Value="@Model.Id" />
    }

    <!--НАЗВАНИЕ-->
    <div class="form-group">
        <label class="col-md-2 control-label">Название:</label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" placeholder="Название" />
            @*<span asp-validation-for="Name" class="text-danger"></span>*@
        </div>
    </div>

    <!--ОПИСАНИЕ ДЕЯТЕЛЬНОСТТ-->
    <div class="form-group">
        <label class="col-md-2 control-label">Описание деятельности:</label>
        <div class="col-md-10">
            <textarea asp-for="ActivityDescription" class="form-control" id="Description" style="resize: vertical;" placeholder="Описание"></textarea>
            @*<span asp-validation-for="ActivityDescription" class="text-danger"></span>*@
        </div>
    </div>

    <!--ЛОГО-->
    <div class="form-group">
        <label class="col-md-2 control-label">Логотип компании:</label>
        @if (Model.LogoImageInBase64 == null)
        {
            <div class="form-group">
                <div class="col-md-8">
                    <div id="images">
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <div class="col-md-8">
                    <div id="images">
                        @foreach (var imageViewModel in Model.ImageViewModels)
                        {
                            <div style="float:left;position: relative;margin-left:15px;margin-top:10px;" id="imgthumb_@imageViewModel.Id" class="imagethumbcell">
                                <img class="thumb" src='@imageViewModel.ImageInBase64' />
                                <div style="position:absolute; left:70px; top:-10px;" id="delbtn_@imageViewModel.Id" class="imagedeletebuttoncell">
                                    <a class='btn btn-default' onclick="deleteCompanyImage('@imageViewModel.goodImageIds');"><span class="imagedeletebutton">x</span></a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        }
        <div class="col-md-2"></div>
        <div class="form-group">
            <div class="col-md-3">
                <a class='btn btn-default' style="height:35px; margin-bottom:5px;margin-left:25px;">
                    Загрузить логотип ...
                    <input type="file"
                            id="loadfile"
                            name="newimages"
                            style="position: absolute;z-index: 2; top: 0; left: 0; opacity: 0; background-color: transparent;color: transparent;"
                            onchange='saveImage();'>
                </a>
            </div>
            <input asp-for="companyImagesIds" type="hidden" id="companyImagesIds" readonly="readonly" value="@Model.companyImagesIds" />
        </div>
    </div>

    <!--ТЕЛЕФОН-->
    @*TODO: Дополнить нужными хелперами для модели и валидацией*@
    <div class="form-group">
        <label class="col-md-2 control-label">Телефон:</label>
        <div class="col-md-10">
            <input asp-for="Telephone" class="form-control" placeholder="Телефон" />
            @*<span asp-validation-for="Telephone" class="text-danger"></span>*@
        </div>
    </div>

    <!--EMAIL-->
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label">Email:</label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" placeholder="Email" />
            @*<span asp-validation-for="Email" class="text-danger"></span>*@
        </div>
    </div>

    <!--ПАРОЛЬ-->
    <!--<div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label">Пароль:</label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" placeholder="Пароль" />
            @*<span asp-validation-for="Password" class="text-danger"></span>*@
        </div>
    </div>
    -->
    <!--ПОДТВЕРЖДЕНИЕ ПАРОЛЯ-->
    <!--<div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label">Подтвердите пароль:</label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" placeholder="Подтвердите пароль" />
            @*<span asp-validation-for="ConfirmPassword" class="text-danger"></span>*@
        </div>
    </div>
        -->
    <!--СООБЩЕНИЯ ВАЛИДАЦИИ-->
    <div class="form-group">
        <br />
        <label class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-right">
            <button type="submit" class="btn btn-primary col-md-2" style="margin-top: 5px;">Сохранить</button>
        </div>
    </div>

</form>

<script type="text/javascript">
    //по сути дублирует метод  deleteCompanyImage так как лого у компании может быть только одно
    function deleteCompanyLogoAndBack() {
        var formData = new FormData();
        formData.append('companyImagesIds', $("#companyImagesIds").val());
        $.ajax({
            url: "/Account/DeleteCompanyImages/",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function () {
                //ничего не надо делать кроме как вернуться назад,
                history.back();
            }
        });
    };

    function deleteCompanyImage(companyImagesIds) {
            var formData = new FormData();
            formData.append('companyImagesIds', companyImagesIds);
            $.ajax({
                url: "/Account/DeleteCompanyImage/",
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (idOfDeletedIm) {
                    //РЕДАКТИРУЕМ СПИСОК ТЕКЦЩИХ ИЗОБРАЖЕНИЙ ТОВАРА
                    //берем исходный список изображений в виде строки
                    var companyImagesIds = $("#companyImagesIds").val();
                    //получаем из этого массив
                    var tmpIdsArr = companyImagesIds.split('_');
                    //удаляем последний элемент из массива так как он пустой
                    tmpIdsArr.splice(tmpIdsArr.length-1, 1);
                    //получаем индекс удаляемого изображения в массиве и удаляем его из массива
                    var idxOfDeletedIm = tmpIdsArr.indexOf(idOfDeletedIm);
                    if (idxOfDeletedIm == -1) return;
                    tmpIdsArr.splice(idxOfDeletedIm, 1);
                    //новый список id изображений  товара
                    //companyImagesIds = tmpIdsArr.join('_') + "_";
                    //у нас только одно лого для компаниЙ, поэтому вычищаем полностью поле companyImagesIds
                    companyImagesIds = "";
                    $("#companyImagesIds").val(companyImagesIds);
                    //удаляем из DOM
                    $("#imgthumb_" + idOfDeletedIm).remove();
                    $("#delbtn_" + idOfDeletedIm).remove();
                }
            });

        };

        function saveImage() {
            //берем изображение
            var image = $('#loadfile')[0].files[0];
            //ПРОВЕРКИ
                //должен быть только один логотип
                var isExist = $("#companyImagesIds").val();
                if (isExist != "") return;
                //если оно есть
                if (image == undefined) return;
                //если оно подходящего размера (не более 300Кб)
                if (image.size > 300000) return;
                //если расширение подходит
                var ext = image.name.substring(image.name.lastIndexOf('.') + 1).toLowerCase();
                if (ext != "gif" && ext != "png" && ext != "jpeg" && ext != "jpg") return;
                //если оно подходящего типа - mimetype
                var imageType = /^image\//;
                if (imageType.test(image.type.match)) return;

            //записываем в БД
            var goodId = $("#Id").val();
            var formData = new FormData();
            formData.append('newimages', image);
            formData.append('Id', goodId);
            $.ajax({
                url: "/Account/AddCompanyImage/",
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (image) {
                    $.ajax({
                        url: "/Account/GetImageForThumb/" + image.id, //здесь просто достается изображение из БД
                        type: 'GET',
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function (data) {
                            //добавление в скрытое поле id изображений нового id изображения
                            var newImagesIds = $("#companyImagesIds").val() + data.id + "_";
                            $("#companyImagesIds").val(newImagesIds);
                            //отображение thumb только что добавленного изображения
                            var image = "<div style='float:left;position: relative;margin-left:15px;margin-top:10px;' id='imgthumb_" + data.id + "' class = 'imagethumbcell'> \
                                                <img class='thumb' src='" + data.imageInBase64 + "' /> \
                                                <div style='position:absolute; left:70px; top:-10px;' id='delbtn_" + data.id + "' class ='imagedeletebuttoncell'> \
                                                    <a class='btn btn-default' onclick = \"deleteCompanyImage('" + data.goodImageIds + "');\"> \
                                                        <span class='imagedeletebutton'>x</span> \
                                                    </a> \
                                                </div> \
                                            </div>";
                            $("#images").append(image);
                        }
                    });
                }
            });
        }
</script>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

BizMall/src/BizMall/Views/AdminProfile/PrivatePersonProfileEditView.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using BizMall.ViewModels.AccountViewModels

@*для создания PrivatePerson используется таже самая viewmodel что и для компании - просто некоторые поля(картинки) скрыты*@
@model BizMall.ViewModels.AccountViewModels.CreateEditCompanyViewModel
@{
    ViewData["Title"] = "Регистрация";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="AdminCompanyProfile" asp-action="EditProfile" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
    <hr />
    <!--ИМЯ-->
    <div class="form-group">
        <label class="col-md-2 control-label">Вас зовут:</label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" placeholder="Название" />
            @*<span asp-validation-for="Name" class="text-danger"></span>*@
        </div>
    </div>

    <!--ТЕЛЕФОН-->
    @*TODO: Дополнить нужными хелперами для модели и валидацией*@
    <div class="form-group">
        <label class="col-md-2 control-label">Телефон:</label>
        <div class="col-md-10">
            <input asp-for="Telephone" class="form-control" placeholder="Телефон" />
            @*<span asp-validation-for="Telephone" class="text-danger"></span>*@
        </div>
    </div>

    <!--EMAIL-->
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label">Email:</label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" placeholder="Email" />
            @*<span asp-validation-for="Email" class="text-danger"></span>*@
        </div>
    </div>

    <!--ПАРОЛЬ-->
    <!--<div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label">Пароль:</label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" placeholder="Пароль" />
            @*<span asp-validation-for="Password" class="text-danger"></span>*@
        </div>
    </div>
        -->

    <!--ПОДТВЕРЖДЕНИЕ ПАРОЛЯ-->
    <!--<div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label">Подтвердите пароль:</label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" placeholder="Подтвердите пароль" />
            @*<span asp-validation-for="ConfirmPassword" class="text-danger"></span>*@
        </div>
    </div>
    -->

    <!--СООБЩЕНИЯ ВАЛИДАЦИИ-->
    <div class="form-group">
        <br />
        <label class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-right">
            <button type="submit" class="btn btn-primary col-md-2" style="margin-top: 5px;">Сохранить</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}