BizMall/src/BizMall/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using BizMall.Data.Repositories.Abstract;
using BizMall.ViewModels.AdminCompanyArticles;
using BizMall.Models.CompanyModels;
using BizMall.Models.CommonModels;
using BizMall.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using ArticleList.Models.CommonModels;
using Microsoft.Extensions.Options;

namespace BizMall.Controllers
{
    /// <summary>
    /// ctor
    /// </summary>
    [Authorize]
    public class AdminCategoriesController : Controller
    {
        private readonly IRepositoryArticle _repositoryArticle;
        private readonly IRepositoryCategory _repositoryCategory;
        private readonly AppSettings _settings;

        public AdminCategoriesController(IRepositoryArticle repositoryArticle,
                                        IRepositoryCategory repositoryCategory,
                                            IOptions<AppSettings> settings)
        {
            _repositoryArticle = repositoryArticle;
            _repositoryCategory = repositoryCategory;
            _settings = settings.Value;
        }

        public IActionResult Categories()
        {
            ViewBag.CategoriesVM = _repositoryCategory.Categories().ToList(); 

            ViewData["Title"] = _settings.ApplicationTitle + "Администрирование: Категории";
            ViewData["HeaderTitle"] = _settings.HeaderTitle;
            ViewData["FooterTitle"] = _settings.FooterTitle;
            ViewBag.ActiveSubMenu = "Категории";
            return View();
        }

        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            ViewData["Title"] = _settings.ApplicationTitle + "Администрирование: Добавление/Редактирование категории";
            ViewData["HeaderTitle"] = _settings.HeaderTitle;
            ViewData["FooterTitle"] = _settings.FooterTitle;
            ViewBag.ActiveSubMenu = "Категории";

            if (id != 0)
                return View(_repositoryCategory.GetCategoryById(id));
            else
                return View(new Category() { CategoryType = CategoryType.News});
        }
        [HttpPost]
        public IActionResult EditCategory(Category model)
        {

            _repositoryCategory.SaveCategory(model);

            return RedirectToAction("Categories");
        }

        /// <summary>
        /// удаление товара
        /// </summary>
        /// <param name="goodId"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult DeleteCategory(int itemId)
        {
            if (itemId != 0)
            {
                _repositoryCategory.DeleteCategory(itemId);
            }
            return RedirectToAction("Categories");
        }

        [HttpPost]
        public JsonResult CategoryArticlesCount(int catId)
        {
            var category = _repositoryCategory.GetCategoryById(catId);
            PagingInfo pagingInfo;
            var Items = _repositoryArticle.CategoryArticlesFullInformation(category.EnTitle, 1, out pagingInfo).ToList();

            var CategoryArticlesCount = pagingInfo.TotalItems;
            return Json(CategoryArticlesCount);
        }
    }
}

BizMall/src/BizMall/Views/AdminCategories/Categories.cshtml
@{
    Layout = "_AdminLayout";
}

<br />

<!--КНОПКА СОЗДАНИЯ ПОЗИЦИИ-->
<div>
    <div style="margin-right:10px;margin-bottom:5px;">
        <a class="btn btn-primary btn-newpos" role="button" asp-controller="AdminCategories" asp-action="EditCategory">Новая категория</a>
    </div>
</div>

<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Название категории</th>
            <th>Название категории(лат.)</th>
            <th>Тип категории</th>
            <th>Родительская категория</th>
            <th>Кол-во статей</th>
            <th>Опции</th>
        </tr>
        </thead>
        @foreach (var cat in ViewBag.CategoriesVM)
        {
            <tr>
                <!--CATEGORY TITLE-->
                <td>
                    <a asp-controller="AdminCategories" asp-action="EditCategory" asp-route-id="@cat.Id">@cat.Title</a>
                </td>
                <!--CATEGORY ENTITLE-->
                <td>
                    @cat.EnTitle
                </td>
                <!--CATEGORY TYPE-->
                <td>
                    @cat.CategoryType
                </td>
                <!--PARENT CATEGORY TITLE-->
                @if (@cat.ParentCategory != null)
                    {<td>@cat.ParentCategory.Title</td>}
                else
                    {<td> -</td >}


                <!--ARTICLES COUNT-->
                @{
                    string idac = cat.Id.ToString() + "articlescount";
                }

                <td style="width:15%;text-align:center;">
                    
                        <a class="articlesCount"  onclick='CategoryArticlesCount(@cat.Id);'></a>
                        @*<a class="btn btn-primary articlesCount" role="button" onclick='CategoryArticlesCount(@cat.Id);'>статей...?</a>*@
                        <span id="@idac" ></span>
                    
                </td>
                <!--OPTIONS-->
                <td style="width: 10%;"><a class="btn btn-primary" role="button" asp-controller="AdminCategories" asp-action="DeleteCategory" asp-route-itemId="@cat.Id">Удалить</a></td>
            </tr>
        }
    </table>
</div>

<script type="text/javascript">
    //показываем сколько статей 
    $(document).ready(function () {
        $(".articlesCount").click();
    });


    function CategoryArticlesCount(catId) {
        //отправить запрос на обновление статусов
        var formData = new FormData();
        formData.append('catId', catId);
        $.ajax({
            url: "/AdminCategories/CategoryArticlesCount",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function (articlescount) {
                var spanid = catId + "articlescount";
                $("#"+spanid).html(articlescount);
            }
        });
    }


    //function Archieve() {
    //    //перебрать все checkbox(checkedToDoSmth) на странице
    //    var checkedGoods = "";
    //    $("input[name='checkedToDoSmth']").each(function () {
    //        if ($(this)[0].checked == true) {
    //            checkedGoods += $(this).val() + "_";
    //        }
    //    });

    //    //отправить запрос на обновление статусов
    //    var formData = new FormData();
    //    formData.append('checkedGoods', checkedGoods);
    //    $.ajax({
    //        url: "/AdminCompanyGoods/ArchieveGoods",
    //        type: 'POST',
    //        data: formData,
    //        processData: false,
    //        contentType: false,
    //        success: function () {
    //            window.location.replace("/AdminCompanyGoods/Goods?goodsStatus=1");
    //        }
    //    });
    //}

    //function Activate() {
    //    //перебрать все checkbox(checkedToDoSmth) на странице
    //    var checkedGoods = "";
    //    $("input[name='checkedToDoSmth']").each(function () {
    //        if ($(this)[0].checked == true) {
    //            checkedGoods += $(this).val() + "_";
    //        }
    //    });

    //    //отправить запрос на обновление статусов
    //    var formData = new FormData();
    //    formData.append('checkedGoods', checkedGoods);
    //    $.ajax({
    //        url: "/AdminCompanyGoods/ActivateGoods",
    //        type: 'POST',
    //        data: formData,
    //        processData: false,
    //        contentType: false,
    //        success: function () {
    //            window.location.replace("/AdminCompanyGoods/Goods?goodsStatus=0");
    //        }
    //    });
    //}
</script>

BizMall/src/BizMall/Views/AdminCategories/EditCategory.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@using BizMall.ViewModels.AccountViewModels

@model BizMall.Models.CompanyModels.Category

@{
    ViewData["Title"] = "Новая категория";
    Layout = "_AdminLayout";
}

<script type="text/javascript">

    function checkCategoryType(type) {
        $("#CategoryType").val(type);
        $(".ParentCategories").hide();
        $("#" + type + "ParentCategories").show();
        $("#CurrentCatName").val('');
        $("#CurrentCatId").val('');
    }

    $(document).ready(function () {
        $(".nestedcat").click(function () {
            var parent = $(this).parent().parent().prev().html();
            var spanbeg = parent.indexOf('<');
            //вырезаем слово родительской категории и соединяем его с названием дочерней категории
            var tmp = parent.substring(0, spanbeg).trim() + "/" + $(this).html();
            tmp = tmp.trim();

            $("#CurrentCatName").val(tmp);
            $("#CurrentCatId").val($(this).attr('id'));
            return;
        });
    });

    $(document).ready(function () {
        $(".cat").click(function () {
            $("#CurrentCatName").val($(this).html());
            $("#CurrentCatId").val($(this).attr('id'));
            return;
        });

    });
</script>

<h3>@ViewData["Title"]</h3>
<form asp-controller="AdminCategories" asp-action="EditCategory" method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
    <hr />
    <!--Id добавляемого/редактируемого товара-->
    @if (Model.Id != 0)
    {
        <input asp-for="Id" type="hidden" class="form-control" id="Id" readonly="readonly" Value ="@Model.Id" />
    }
    <!--НАИМЕНОВАНИЕ-->
    <div class="form-group">
        <label asp-for="Title" class="col-md-2 control-label">Тип категории</label>
        <div class="col-md-1">
            <input asp-for="CategoryType" type="hidden" id ="CategoryType" name="CategoryType" Value ="@Model.CategoryType"> 
        </div>
        <div class="col-md-8">
            @if (@Model.CategoryType == BizMall.Models.CompanyModels.CategoryType.News)
            {
                <div>
                    <input type="radio" name="type" onclick="checkCategoryType('News');" value="Новости" checked="checked"> Новости <br /><br />
                    <input type="radio" name="type" onclick="checkCategoryType('Suggestions');" value="Предложения"> Предложения <br /><br />                    
                    <input type="radio" name="type" onclick="checkCategoryType('Articles');" value="Статьи" > Статьи
                </div>
            }
            @if (@Model.CategoryType == BizMall.Models.CompanyModels.CategoryType.Suggestions)
            {
                <div>
                    <input type="radio" name="type" onclick="checkCategoryType('News');"  value="Новости"> Новости <br /><br />
                    <input type="radio" name="type" onclick="checkCategoryType('Suggestions');" value="Предложения" checked="checked" > Предложения <br /><br />
                    <input type="radio" name="type" onclick="checkCategoryType('Articles');" value="Статьи"> Статьи
                </div>
            }
            @if (@Model.CategoryType == BizMall.Models.CompanyModels.CategoryType.Articles)
            {
                <div>
                    <input type="radio" name="type" onclick="checkCategoryType('News');" value="Новости"> Новости <br /><br />
                    <input type="radio" name="type" onclick="checkCategoryType('Suggestions');" value="Предложения"> Предложения <br /><br />
                    <input type="radio" name="type" onclick="checkCategoryType('Articles');" value="Статьи" checked="checked"> Статьи
                </div>
            }
                
        </div>
    </div>

    <!--НАИМЕНОВАНИЕ-->
    <div class="form-group">
        <label asp-for="Title" class="col-md-2 control-label">Название</label>
        <div class="col-md-10" >
            <input asp-for="Title" class="form-control col-md-10" id="Title" placeholder="Наименование"  Value ="@Model.Title"/>
        </div>
    </div>

    <!--КАТЕГОРИИ-->

    @if (@Model.CategoryType == BizMall.Models.CompanyModels.CategoryType.News)
    {
        <div id="NewsParentCategories" class="ParentCategories">@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.News })</div>
        <div id="SuggestionsParentCategories" class="ParentCategories" style="display:none">@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Suggestions })</div>
        <div id="ArticlesParentCategories" class="ParentCategories" style="display:none">@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Articles })</div>
    }
    @if (@Model.CategoryType == BizMall.Models.CompanyModels.CategoryType.Suggestions)
    {
        <div id="NewsParentCategories" class="ParentCategories" style="display:none">@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.News })</div>
        <div id="SuggestionsParentCategories" class="ParentCategories" >@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Suggestions })</div>
        <div id="ArticlesParentCategories" class="ParentCategories" style="display:none">@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Articles })</div>
    }
    @if (@Model.CategoryType == BizMall.Models.CompanyModels.CategoryType.Articles)
    {
        <div id="NewsParentCategories" class="ParentCategories" style="display:none">@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.News })</div>
        <div id="SuggestionsParentCategories" class="ParentCategories" style="display:none">@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Suggestions })</div>
        <div id="ArticlesParentCategories" class="ParentCategories" >@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Articles })</div>
    }
    @*@await Component.InvokeAsync("AllParentCategories", new { cat = Model })*@
     @*@await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Suggestions})
     @await Component.InvokeAsync("AllParentCategories", new { categoryType = BizMall.Models.CompanyModels.CategoryType.Articles})*@
    
    <div class="form-group">
        <div class="col-md-2">
        </div>

        @if (Model?.ParentCategory != null)
        {
            <div class="col-md-3 ">
                <label style="padding-top:20px;">Текущая родительская категория:</label><br />
                <input class="form-control" id="CurrentCatName" readonly="readonly" value="@Model.ParentCategory.Title" />
                <input asp-for="@Model.ParentCategory.Id" type="hidden" class="form-control" id="CurrentCatId" readonly="readonly" value="@Model.ParentCategory.Id" />
                @*<span asp-validation-for="Category" class="text-danger"></span>*@
            </div>
        }
        else
        {
            <div class="col-md-3 ">
                <label style="padding-top:20px;">Текущая родительская категория:</label><br />
                <input class="form-control" id="CurrentCatName" readonly="readonly" />
                <input asp-for="@Model.ParentCategory.Id" type="hidden" class="form-control" id="CurrentCatId" readonly="readonly" />
                @*<span asp-validation-for="Category" class="text-danger"></span>*@
            </div>
        }
    </div>



    <!--ЛАТ НАИМЕНОВАНИЕ-->
    <div class="form-group">
        <label asp-for="EnTitle" class="col-md-2 control-label">Название(латиница)</label>
        <div class="col-md-10">
            <input asp-for="EnTitle" class="form-control col-md-10" id="EnTitle" placeholder="Наименование(латиница)" Value="@Model.EnTitle" />
        </div>
    </div>
   
    <!--metaKeyWords-->
    <div class="form-group">
        <label asp-for="metaKeyWords" class="col-md-2 control-label">Meta-тег Keywords</label>
        <div class="col-md-10">
            <textarea asp-for="metaKeyWords" class="form-control" id="metaKeyWords" style="resize: vertical;" placeholder="metaKeyWords" Value="@Model.metaKeyWords"></textarea>
        </div>
    </div>

    <!--metaDescription-->
    <div class="form-group">
        <label asp-for="metaDescription" class="col-md-2 control-label">Meta-тег Description</label>
        <div class="col-md-10">
            <textarea asp-for="metaDescription" class="form-control" id="metaDescription" style="resize: vertical;" placeholder="metaDescription" Value="@Model.metaDescription"></textarea>
        </div>
    </div>

    <!--СООБЩЕНИЯ ВАЛИДАЦИИ-->
    <div class="form-group">
        <label class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
    </div>  

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-right">
            <button type="submit" class="btn btn-primary  col-md-2" style="margin-top: 5px;">Сохранить</button>
            <a asp-controller="AdminCategories" asp-action="Categories" class='btn btn-default col-md-2 ' style="margin-left: 5px; margin-top: 5px;">Назад</a>
        </div>
    </div>
</form>



@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}